### ISSUE TITLE
Provide proper workaround for duckietown/duckiefleet

### ISSUE THREAD

**Issue by breandan** [rusi/duckietown.dev.land#29]
Currently, [we are mocking](https://github.com/breandan/Software/blob/d30a464249601a2b5c3bc8c6bca1d5868fabbaf6/Dockerfile#L21) the machines file, instead of injecting the `docker` machine entry during codegen. This file is properly generated by [`make build-machines`](https://github.com/breandan/Software/blob/d30a464249601a2b5c3bc8c6bca1d5868fabbaf6/Makefiles/Makefile.build.mk#L23). We need to provide a better workaround, or determine if we're going to support [duckietown/duckiefleet](https://github.com/duckietown/duckiefleet) going forward. @andreacensi What was the original purpose of cloning duckiefleet during the build process and are we married to this or can you see another alternative? We can support, but it's a bit messy. cc: @rusi

**Comment by AndreaCensi** [comment]
All of that will go away.

---
Andrea Censi - https://censi.science
* Deputy Director, Chair of Dynamic Systems and Control, ETH Zurich.
* Director of Research, nuTonomy (http://nuTonomy.com)
* Chief Technology Officer, Duckietown (http://duckietown.org)

On 22 June 2018 at 01:12:21, breandan (notifications@github.com) wrote:

Currently, we are mocking
<https://github.com/breandan/Software/blob/d30a464249601a2b5c3bc8c6bca1d5868fabbaf6/Dockerfile#L21>
the machines file, instead of injecting the docker machine entry during
codegen. This file is properly generated by make build-machines
<https://github.com/breandan/Software/blob/d30a464249601a2b5c3bc8c6bca1d5868fabbaf6/Makefiles/Makefile.build.mk#L23>.
We need to provide a better workaround, or determine if we're going to
support duckietown/duckiefleet <https://github.com/duckietown/duckiefleet>
going forward. @AndreaCensi <https://github.com/AndreaCensi> What was the
original purpose of cloning duckiefleet during the build process and are we
married to this or can you see another alternative? We can support, but
it's a bit messy. cc: @rusi <https://github.com/rusi>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rusi/duckietown.dev.land/issues/29>, or mute the thread
